language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"

before_install:
  - travis_retry npm install

script:
  - npm test

matrix:
  allow_failures:
    - node_js: "iojs"

notifications:
  irc:
    channels:
      - "irc.freenode.org#bigpipe"
    on_success: change
    on_failure: change
